name: forchetta
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/pizza2.png
    - assets/pizza.png
    - assets/italy.png

  fonts:
    - family: Lobster
      fonts: 
        - asset: fonts/Lobster.ttf

    - family: seriously
      fonts:
        - asset: fonts/seriously.ttf

    - family: freescp
      fonts:
        - asset: fonts/freescp.ttf
  