name: forchetta
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/pizza2.png
    - assets/pizza.png
    - assets/pizza4.png
    - assets/pizza5.png
    - assets/pizza6.png
    - assets/pin.png
    - assets/pizzam.png
    - assets/calendar.png
    - assets/italy.png
    - assets/albon.jpeg
    - assets/carpaccio.jpg
    - assets/ensalada.jpg
    - assets/lasagna.png
    - assets/margarita.jpg
    - assets/piadi.jpg
    - assets/spag.jpg
    - assets/spag2.jpg
    - assets/add.png
    - assets/spaghetti.png


  fonts:
    - family: Lobster
      fonts: 
        - asset: fonts/Lobster.ttf

    - family: seriously
      fonts:
        - asset: fonts/seriously.ttf

    - family: freescp
      fonts:
        - asset: fonts/freescp.ttf
  